steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/adk-demos/warehouse-safety-agent:v1 \
          --build-arg GCP_TOKEN=$$(gcloud auth print-access-token) \
          .
    env:
      - 'DOCKER_BUILDKIT=1'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-demos/warehouse-safety-agent:v1'
